# Generated by Django 5.1.1 on 2024-10-24 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payments_service", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payments",
            old_name="crated_at",
            new_name="created_at",
        ),
    ]
