# Generated by Django 5.1.1 on 2024-10-04 10:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("author", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "cover",
                    models.CharField(
                        blank=True,
                        choices=[("hard cover", "Hard"), ("soft cover", "Soft")],
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "inventory",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "daily_fee",
                    models.DecimalField(decimal_places=2, max_digits=5, null=True),
                ),
            ],
        ),
    ]
