version: "3.9"

services:

  db:
    image: postgres:16.0
    restart: always

    ports:
      - "5432:5432"
    volumes:
      - postgres_data:$PGDATA

    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_HOST: $POSTGRES_HOST
      POSTGRES_PORT: $POSTGRES_PORT

volumes:
  postgres_data: